name: Buzzer-CI
run-name: Running Buzzer tests.
on: [push, pull_request]
jobs:
  Buzzer-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 17
        platform: x64
    - name: Check Buzzer tests
      run: |
           bazel build //...
           bazel test //...
      env:
       CC:   clang
       CXX:  clang++
